name: "dep Jobs Example"

on: [push]

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Step 1"
        run: echo "World"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 2"
        run: echo "Hello"
